
name: UI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [14]

    steps:
      - uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: run build
        run: |
          npm install
          npm run lint
          npm run build
